apiVersion: siqi.dev/v1alpha1
kind: Kluster
metadata:
  name: kluster-0
  finalizers:
  - "siqi.dev/prod-protection"
spec:
  name: kluster-0
  region: "nyc1"
  version: "1.27.4-do.0"
  tokenSecret: "default/dosecret"
  nodePools:
    - count: 3
      name: "dummy-nodepool"
      size: "s-2vcpu-2gb"